# http configuration
api: 
  endpoint: owi-fs-loadtest.veriksystems.com
# mqtt configuration
mqtt:
  endpoint:
  prefix: org/vz-loadtest
# testing agrument configuration
testing:
  user:
    runServiceDelay: 10.0
    startServiceDelay: 900.0
    getDataInterval: 600.0
    realtime:
      interval: 600.0
      period: 30.0
      heartbeatInterval: 6 
  device:
    realtimeInterval: 1.0
    historyInterval: 10.0
  service:
    realtimeLength: 6
